apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
  labels:
    app: up
spec:
  replicas: 1
  selector:
    matchLabels:
      app: up
  template:
    metadata:
      labels:
        app: up
    spec:
      containers:
      - name: app
        image: huarami/uploader:v1
        ports:
        - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  type: NodePort
  selector:
    app: up
  ports:
  - targetPort: 8000
    port: 8000
    nodePort: 30002
