apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
  labels:
    app: up
spec:
  replicas: 2
  selector:
    matchLabels:
      app: up
  template:
    metadata:
      labels:
        app: up
    spec:
      containers:
      - name: app
        image: huarami/uploader:latest
        ports:
        - containerPort: 8000
